name: Deploy react app to GitHub Pages
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Person to greet"
        # Default value if no value is explicitly provided
        default: "World"
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: print node version
        run: node --version
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm run test
      - name: completed job
        run: echo "Job completed successfully"  
     

