name: Greet user
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: echo "Hello, ${{ github.actor }}!"
      - name: Goodbye message
        run: echo "Goodbye, ${{ github.name }}!"
      - name: Print GitHub context
        run: |
          echo "${{toJson(github)}}"
